language: csharp
dist: xenial
mono: none
dotnet: 2.2.100

branches:
  only:
    - master
    - develop

env:
  - PROJECT_DIR=LoadBalancer
  - PROJECT_DIR=LoadBalancer.Logs.Web

before_script:
 - cd LoadBalancer/$PROJECT_DIR
script:
  - dotnet restore
  - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
notifications:
  email:
    on_success: never
    on_failure: always